version: "3.4"

x-services:
  shared-app-be: &shared-app-be
    build:
      context: ./.docker/be/dev
      dockerfile: Dockerfile
    volumes:
      - ./app/be:/app:cached
      - ./var/cache/composer:/var/composer_cache
      - ./var/coverage-reports:/opt/phpstorm-coverage
    working_dir: /app
    user: application
    environment:
      APP_ENV: dev
      PHP_IDE_CONFIG: "serverName=_"
    env_file:
      - .env

services:
  app-be:
    <<: *shared-app-be
    ports:
      - '9001:9000'
      - '8081:8080'
    depends_on:
      - db
      - redis
    entrypoint: bash
    command:
      - -c
      - >-
        xdebug-disable;
        tail -f /dev/null
  app-be-debug:
    <<: *shared-app-be
    entrypoint: bash
    user: application
    command:
      - -c
      - >-
        xdebug-enable;
        tail -f /dev/null
  db:
    image: postgres:17-alpine
    environment:
      POSTGRES_USER: $POSTGRES_USER
      POSTGRES_PASSWORD: $POSTGRES_PASSWORD
      POSTGRES_DB: $POSTGRES_DB
  redis:
    image: redis:7-alpine
  app-fe:
    image: node:22-bookworm
    volumes:
      - ./app/fe:/app
    user: node
    ports:
      - '5173:5173'
    working_dir: /app
    command: ["tail", "-f", "/dev/null"]
